category:
  jq -r '[.[].breadcrumbs.[] | select(.category_id != 0)] | unique_by(.category_id) | .[] | [.category_id, .name] | @csv' ./product-detail/concat-detail.json

product:
  jq -r -f ./queries/detail-concat/product.jq ./product-detail/concat-detail.json | jq -s .

product-spid-urls:
  jq -r -f ./queries/detail-concat/spid.jq ./product-detail/concat-detail.json

[private]
product-category:
  jq -r '.[] | {id, category_id: (.breadcrumbs.[] | select(.category_id != 0) | .category_id)} | [.id, .category_id] | @csv' ./product-detail/concat-detail.json

product-image:
  # jq -s . <({just product-image-temp; just product-variant-image; }) >product-image-merge.json
  jq -r -f ./queries/product-image-merge/merge-to-product-image.jq ./product-image-merge.json

product-image-temp:
  jq -r -f ./queries/detail-concat/product_images.jq ./product-detail/concat-detail.json

product-variant-image:
  jq -r -f ./queries/sub-product-concat/product_variant_image.jq ./sub-product/concat-sub-product.json

option:
  jq -r -f ./queries/detail-concat/option.jq ./product-detail/concat-detail.json

option-value:
  jq -r -f ./queries/detail-concat/option_value.jq ./product-detail/concat-detail.json

[private]
brand:
  jq -r '[.[].brand] | unique_by(.id) | .[] | [.id, .name] | @csv' ./product-detail/concat-detail.json

attribute:
  jq -r -f ./queries/detail-concat/attribute.jq ./product-detail/concat-detail.json

attribute-value:
  jq -r -f ./queries/detail-concat/attribute_value.jq ./product-detail/concat-detail.json

product-attribute-value:
  jq -r -f ./queries/detail-concat/product_attribute_value.jq ./product-detail/concat-detail.json

product-variant:
  jq -r -f ./queries/detail-concat/product_variant.jq ./product-detail/concat-detail.json

option-value-product-variant:
  jq -r -f ./queries/detail-concat/option_value_product_variant.jq ./product-detail/concat-detail.json
